language: node_js
sudo: true

node_js:
  - '10.15'
  - '12.14'
  - '13.6'

cache:
  - npm
  - yarn

install:
  - travis_retry npm ci

script:
  - npm run build
  - npm run test

after_success:
  - codecov
