name: Node CI

on: [push, pull_request]

jobs:
  default:
    strategy:
      matrix:
        node: [10, 12, 13]
        os: [macos-latest, windows-latest, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      uses: actions/checkout@v1
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      run: npm ci
      run: npm run test
      env:
        CI: 'true'
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
